language: cpp
compiler: clang
install:
# libstdc++-4.8-dev
#  * required because http://gcc.gnu.org/bugzilla/show_bug.cgi?id=53841
#  * using https://github.com/dream-framework/tagged-format/blob/master/.travis.yml as reference
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - sudo apt-get -qq install libstdc++-4.8-dev 
# required x11 and opengl libs
    - sudo apt-get -qq install xorg-dev
    - sudo apt-get -qq install libglu1-mesa-dev
# cmake
    - sudo apt-get -qq install cmake
